name = "RiaFst"
author = "liziluyu"
version = "3.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ffba1d745a5e1dfb853374403dfd575cc8f744357e3f2f8b78d5474f953d71b8"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
