name = "RiaFst"
author = "liziluyu"
version = "3.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a750c5fb5db300088138486efd28573b7ba69ab82e4f091cd9833f1690e2f46e"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
