name = "RiaFst"
author = "liziluyu"
version = "3.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91643eb9879d70a7afe02b55b5f2930b0f0d04c6bb23dd96d3c1b4cf9b10887c"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
